/**
 * Playback e2e test — Task 10 (Phase 2)
 *
 * CODEC CAVEAT:
 *   Playwright's bundled Chromium does NOT decode proprietary H.264/AAC.
 *   We therefore do NOT assert real frame decoding or currentTime advancing.
 *   Instead we verify WIRING deterministically:
 *     1. Clicking Play mounts the Player (decision API request fires + player
 *        div is rendered in the DOM).
 *     2. Progress PUT → continue-watching GET → home row render → progress GET
 *        (full round-trip via page.evaluate fetch, bypassing codec requirement).
 */

import { test, expect, type Page } from "@playwright/test";
import path from "node:path";
import os from "node:os";
import fs from "node:fs";
import { execSync } from "node:child_process";

test.describe.configure({ mode: "serial" });

// ── Seed constants ────────────────────────────────────────────────────────────
const LIBRARY_ID = "playbklibrary0000000001";
const SECTION_ID = "playbksection0000000001";
const ITEM_ID    = "playbkitem00000000000001";
const FILE_ID    = "playbkfile0000000000001";

const ADMIN_EMAIL    = "playback@home.lan";
const ADMIN_PASSWORD = "longenough";

const METADATA_DIR = process.env.METADATA_DIR ?? "./data/metadata";
const POSTER_REL   = "poster/playbk.jpg";
const POSTER_ABS   = path.resolve(METADATA_DIR, POSTER_REL);

// Tiny 1×1 JPEG (same as library.spec.ts)
const TINY_JPEG = Buffer.from(
  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a" +
  "HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy" +
  "MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEB" +
  "AxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAUAQEAAAAAAAAA" +
  "AAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCwABmX/9k=",
  "base64",
);

// Video file for the seeded MediaFile (generated by ffmpeg)
const VIDEO_PATH = path.join(os.tmpdir(), "orbix-playback-seed.mp4");

// ── DB seed / clean ───────────────────────────────────────────────────────────

async function seedDb() {
  process.env.DATABASE_URL ??= "postgresql://orbix:orbix@localhost:1062/orbix";
  const { prisma } = await import("@orbix/db");
  const { hashPassword } = await import("@orbix/core");

  // Clean any leftovers
  await prisma.playbackState.deleteMany({ where: { mediaItemId: ITEM_ID } });
  await prisma.mediaFile.deleteMany({ where: { id: FILE_ID } });
  await prisma.mediaItem.deleteMany({ where: { id: ITEM_ID } });
  await prisma.section.deleteMany({ where: { id: SECTION_ID } });
  await prisma.library.deleteMany({ where: { id: LIBRARY_ID } });
  // Wipe ALL accounts (not just this email): the DB enforces a single admin
  // (partial unique index on isAdmin), so a leftover admin from an earlier spec
  // (e.g. onboarding) would make the create() below fail with P2002.
  await prisma.account.deleteMany();

  // Create the admin account directly (bypassing the setup API race condition).
  // This ensures the playback spec can always log in regardless of whether the
  // onboarding or library spec ran first and completed setup.
  const passwordHash = await hashPassword(ADMIN_PASSWORD);
  await prisma.account.create({
    data: { email: ADMIN_EMAIL, passwordHash, isAdmin: true },
  });

  // Profile creation is handled in doOnboarding via the browser UI so it's
  // resilient to other test specs' afterAll deleting all profiles.

  // Write tiny poster
  await fs.promises.mkdir(path.dirname(POSTER_ABS), { recursive: true });
  await fs.promises.writeFile(POSTER_ABS, TINY_JPEG);

  // Generate a minimal valid MP4 with ffmpeg (3-second testsrc)
  execSync(
    `ffmpeg -y -f lavfi -i testsrc=duration=3:size=320x240:rate=24 ` +
    `-c:v libx264 -pix_fmt yuv420p -t 3 ${VIDEO_PATH}`,
    { stdio: "pipe" },
  );

  await prisma.library.create({
    data: {
      id: LIBRARY_ID,
      name: "Playback Library",
      sections: {
        create: {
          id: SECTION_ID,
          name: "Playback Section",
          order: 0,
          items: {
            create: {
              id: ITEM_ID,
              title: "Playback Movie",
              sortTitle: "playback movie",
              year: 2024,
              overview: "A playback test movie.",
              posterPath: POSTER_REL,
              matchState: "matched",
              files: {
                create: {
                  id: FILE_ID,
                  path: VIDEO_PATH,
                  container: "mp4",
                  videoCodec: "h264",
                  audioCodecs: ["aac"],
                  durationSec: 3,
                  width: 320,
                  height: 240,
                },
              },
            },
          },
        },
      },
    },
  });

  await prisma.$disconnect();
}

async function cleanDb() {
  process.env.DATABASE_URL ??= "postgresql://orbix:orbix@localhost:1062/orbix";
  const { prisma } = await import("@orbix/db");

  await prisma.playbackState.deleteMany({
    where: { mediaItemId: ITEM_ID },
  });
  await prisma.mediaFile.deleteMany({ where: { id: FILE_ID } });
  await prisma.mediaItem.deleteMany({ where: { id: ITEM_ID } });
  await prisma.section.deleteMany({ where: { id: SECTION_ID } });
  await prisma.library.deleteMany({ where: { id: LIBRARY_ID } });
  await prisma.profile.deleteMany();
  await prisma.account.deleteMany({ where: { email: ADMIN_EMAIL } });
  await prisma.$disconnect();

  try { fs.unlinkSync(POSTER_ABS); } catch { /* ignore */ }
  try { fs.unlinkSync(VIDEO_PATH); } catch { /* ignore */ }
}

// ── Onboarding helper ─────────────────────────────────────────────────────────
// seedDb() pre-creates the admin account via Prisma so we can always log in.
// The page may land on /setup (if no other test has run yet) or /login (if
// another spec already completed setup). We navigate to /login in either case.
// The "Watcher" profile is created via the browser UI here so it's resilient
// to other specs' afterAll deleting all profiles.

async function doOnboarding(page: Page) {
  await page.goto("http://localhost:1060/");
  await page.waitForURL(/\/(setup|login|profiles|$)/, { timeout: 15_000 });

  if (page.url().includes("/setup")) {
    // Our account already exists in the DB (from seedDb), but the home page
    // redirected to /setup because no OTHER account existed before seedDb ran.
    // Navigate directly to /login to use our pre-created credentials.
    await page.goto("http://localhost:1060/login");
    await page.waitForURL(/\/login/, { timeout: 10_000 });
  }

  if (page.url().includes("/login")) {
    await page.getByLabel("Email").fill(ADMIN_EMAIL);
    await page.getByLabel("Password").fill(ADMIN_PASSWORD);
    await page.getByRole("button", { name: /sign in/i }).click();
    await expect(page).toHaveURL(/\/profiles/, { timeout: 15_000 });
  }

  // On the profiles page: create "Watcher" if it doesn't exist, then select it
  await page.waitForURL(/\/(profiles|$)/, { timeout: 15_000 });
  if (page.url().includes("/profiles")) {
    const watcher = page.getByText("Watcher");
    if (!(await watcher.isVisible())) {
      await page.getByRole("button", { name: /add profile/i }).click();
      await page.getByLabel("Name").fill("Watcher");
      await page.getByRole("button", { name: /save/i }).click();
    }
    await page.getByText("Watcher").click();
    await expect(page).toHaveURL(/\/$/, { timeout: 15_000 });
  }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test.describe("Playback wiring", () => {
  test.beforeAll(async () => {
    await seedDb();
  });

  test.afterAll(async () => {
    await cleanDb();
  });

  // ── Test 1: clicking Play mounts the Player and fires the decision request ──
  test("Play button mounts Player and fires /decision request", async ({ page }) => {
    await doOnboarding(page);
    await page.goto(`http://localhost:1060/title/${ITEM_ID}`);

    // Set up request intercept BEFORE clicking Play
    const decisionReq = page.waitForRequest(
      (req) => req.url().includes(`/api/play/${FILE_ID}/decision`),
      { timeout: 20_000 },
    );

    // The Play button should be enabled (file exists with an id)
    const playBtn = page.getByRole("button", { name: /^Play$/i });
    await expect(playBtn).toBeEnabled({ timeout: 15_000 });
    await playBtn.click();

    // The decision API request MUST fire (proves Player mounted + useEffect ran)
    await decisionReq;

    // The Player renders a div with our aspect-video class once the decision resolves
    await expect(page.locator(".aspect-video").first()).toBeVisible({ timeout: 20_000 });
  });

  // ── Test 2: progress / continue-watching / resume round-trip ─────────────
  // (Done via page.evaluate fetch so it's codec-agnostic and fully deterministic)
  test("progress → continue-watching → home row → resume round-trip", async ({ page }) => {
    await doOnboarding(page);

    // Must be on a page with the session cookie in scope before using page.evaluate
    await page.goto("http://localhost:1060/");
    await expect(page).toHaveURL(/\/$/, { timeout: 15_000 });

    // PUT progress (positionSec: 60 out of 180 → ~33% → not finished)
    const putResult = await page.evaluate(async (itemId: string) => {
      const res = await fetch(`/api/items/${itemId}/progress`, {
        method: "PUT",
        credentials: "include",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ positionSec: 60, durationSec: 180 }),
      });
      return { ok: res.ok, status: res.status, body: await res.json() };
    }, ITEM_ID);
    expect(putResult.ok, `PUT /items/:id/progress failed: ${JSON.stringify(putResult)}`).toBe(true);

    // GET continue-watching — item must appear
    const cwItems = await page.evaluate(async () => {
      const res = await fetch("/api/continue-watching", { credentials: "include" });
      return await res.json() as { mediaItemId: string }[];
    });
    expect(
      cwItems.some((i) => i.mediaItemId === ITEM_ID),
      `Expected ${ITEM_ID} in continue-watching, got: ${JSON.stringify(cwItems)}`,
    ).toBe(true);

    // Reload home page — ContinueWatching row must show "Continue Watching" heading
    // and a card linking to the seeded movie. Use the link role to disambiguate from the
    // "Because you watched Playback Movie" smart-row heading (which is an <h2>, not a link).
    await page.reload();
    await expect(page.getByText("Continue Watching")).toBeVisible({ timeout: 15_000 });
    await expect(
      page.getByRole("link", { name: /Playback Movie/i }).first(),
    ).toBeVisible({ timeout: 15_000 });

    // Navigate to title page — GET /api/items/:id/progress must return positionSec: 60
    // (This is what the Player would use for resume on next load)
    const progress = await page.evaluate(async (itemId: string) => {
      const res = await fetch(`/api/items/${itemId}/progress`, { credentials: "include" });
      return await res.json() as { positionSec: number; durationSec: number; finished: boolean };
    }, ITEM_ID);
    expect(progress.positionSec).toBe(60);
    expect(progress.finished).toBe(false);
  });
});
